In [1]:
import os
import numpy as np
import torch
from PIL import Image

import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection.mask_rcnn import MaskRCNNPredictor

from engine import train_one_epoch, evaluate
import utils
import transforms as T

In [2]:
print(os.path)

<module 'posixpath' from '/Users/fuchang.zfc/anaconda3/envs/deeplearning/lib/python3.10/posixpath.py'>


In [3]:
print(os.path.join('PennFudanPed',"PNGImages"))


PennFudanPed/PNGImages


In [6]:
print(os.path.join('PennFudanPed',"PNGImages"))

PennFudanPed/PNGImages


In [11]:
sorted(os.listdir("PennFudanPed/PNGImages"))

['FudanPed00001.png',
 'FudanPed00002.png',
 'FudanPed00003.png',
 'FudanPed00004.png',
 'FudanPed00005.png',
 'FudanPed00006.png',
 'FudanPed00007.png',
 'FudanPed00008.png',
 'FudanPed00009.png',
 'FudanPed00010.png',
 'FudanPed00011.png',
 'FudanPed00012.png',
 'FudanPed00013.png',
 'FudanPed00014.png',
 'FudanPed00015.png',
 'FudanPed00016.png',
 'FudanPed00017.png',
 'FudanPed00018.png',
 'FudanPed00019.png',
 'FudanPed00020.png',
 'FudanPed00021.png',
 'FudanPed00022.png',
 'FudanPed00023.png',
 'FudanPed00024.png',
 'FudanPed00025.png',
 'FudanPed00026.png',
 'FudanPed00027.png',
 'FudanPed00028.png',
 'FudanPed00029.png',
 'FudanPed00030.png',
 'FudanPed00031.png',
 'FudanPed00032.png',
 'FudanPed00033.png',
 'FudanPed00034.png',
 'FudanPed00035.png',
 'FudanPed00036.png',
 'FudanPed00037.png',
 'FudanPed00038.png',
 'FudanPed00039.png',
 'FudanPed00040.png',
 'FudanPed00041.png',
 'FudanPed00042.png',
 'FudanPed00043.png',
 'FudanPed00044.png',
 'FudanPed00045.png',
 'FudanPed

In [14]:
print(Image.open("PennFudanPed/PNGImages/FudanPed00001.png").convert("RGB"))

<PIL.Image.Image image mode=RGB size=559x536 at 0x7FD1A8F10310>


In [15]:
print(Image.open("PennFudanPed/PNGImages/FudanPed00001.png"))

<PIL.PngImagePlugin.PngImageFile image mode=RGB size=559x536 at 0x7FD1B96197E0>


In [17]:
np.array(Image.open("PennFudanPed/PedMasks/FudanPed00001_mask.png"))

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [21]:
np.unique(Image.open("PennFudanPed/PedMasks/FudanPed00001_mask.png"))

array([0, 1, 2], dtype=uint8)

In [24]:
np.unique(Image.open("PennFudanPed/PedMasks/FudanPed00001_mask.png"))[:,None, None]

array([[[0]],

       [[1]],

       [[2]]], dtype=uint8)

In [32]:
arr = np.array([1,2,3,4,2,1])
print(np.where(2))

(array([0]),)


In [33]:
res = torch.as_tensor([[0,0,0,0], [1,1,1,1]], dtype=torch.float32)
print(res)

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.]])


In [35]:
print(torch.ones((10,), dtype=torch.int64))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [43]:
indices = torch.randperm(100).tolist()
print(indices[:-50])
print(indices[-50:])

[32, 48, 87, 71, 12, 95, 74, 38, 54, 53, 77, 21, 86, 79, 18, 50, 75, 63, 9, 43, 25, 73, 93, 36, 15, 11, 16, 52, 22, 78, 37, 98, 81, 99, 24, 90, 19, 10, 26, 7, 1, 46, 2, 44, 31, 96, 76, 69, 61, 28]
[6, 27, 85, 80, 17, 45, 13, 56, 5, 33, 55, 3, 82, 23, 41, 8, 59, 84, 67, 39, 35, 40, 34, 49, 58, 30, 83, 62, 97, 94, 29, 51, 88, 60, 91, 68, 0, 47, 64, 89, 65, 57, 4, 14, 20, 42, 70, 66, 92, 72]
